# Generated by Django 4.2.4 on 2023-08-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null=True)),
                ('email', models.CharField(default='none', max_length=155)),
                ('subject', models.CharField(max_length=155, null=True)),
                ('feed', models.TextField(null=True)),
            ],
        ),
    ]
